plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
}

version = '1.1.0'
group = 'meldexun.memoryutil'
base.archivesName = 'MemoryUtil'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

jar {
    from('LICENSE') {
        rename { 'META-INF/' + it }
    }

    manifest.attributes([
        'Built-By': 'Meldexun',
        'Specification-Title': base.archivesName,
        'Specification-Version': version,
        'Specification-Vendor': 'Meldexun',
        'Implementation-Title': base.archivesName,
        'Implementation-Version': version,
        'Implementation-Vendor': 'Meldexun',
        'Implementation-Timestamp': new Date().format("yyyy-MM-dd HH:mm:ss")
    ])
}
